
package com.entrenamosuy.web.publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioNoEncontradoExceptionWrapper", targetNamespace = "http://publicar.view.tarea1.entrenamosuy.com/")
public class UsuarioNoEncontradoExceptionWrapper_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNoEncontradoExceptionWrapper faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNoEncontradoExceptionWrapper_Exception(String message, UsuarioNoEncontradoExceptionWrapper faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioNoEncontradoExceptionWrapper_Exception(String message, UsuarioNoEncontradoExceptionWrapper faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.entrenamosuy.web.publicar.UsuarioNoEncontradoExceptionWrapper
     */
    public UsuarioNoEncontradoExceptionWrapper getFaultInfo() {
        return faultInfo;
    }

}
